version: "2"

services:
  mongodb:
    image: "mongo:3.6.23-xenial"
    container_name: "mongodb"
    hostname: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    expose:
      - 27017
      - 28017
    ports:
      - "27017:27017"
      - "28017:28017"

  server:
    build: ./server
    image: "ericka/proyecto_final_server:1.0.0"
    container_name: "server"
    hostname: "server"
    environment:
      SERVICE_NAME: "server"
      DEPLOY_PORT: 8080
      MONGO_DB_URL: "mongodb://admin:pass@mongodb:27017/"
    command: "echo Server!"
    depends_on:
      - mongodb
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8080:8080"

  client:
    build: ./client
    image: "ericka/proyecto_final_client:1.0.0"
    container_name: "client"
    hostname: "client"
    environment:
      SERVICE_NAME: "client"
      SERVER_PORT: 8080
      DEPLOY_PORT: 8081
    command: "echo Client!"
    volumes:
      - ./client:/usr/src/app
    ports:
      - "8081:8081"
